-- Create carts table
create table public.carts (
  id bigint generated by default as identity primary key,
  user_id text not null unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);


