-- Create cart_items table
create table public.cart_items (
  id bigint generated by default as identity primary key,
  cart_id bigint not null references public.carts(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(cart_id, product_id)
);

-- Enable Row Level Security (RLS)
alter table public.cart_items enable row level security;

-- Create policies
create policy "Users can view own cart items" on public.cart_items for select to authenticated using (
  exists (
    select 1 from public.carts
    where id = cart_items.cart_id and user_id = auth.uid()::text
  )
);
