-- Create products table
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric(10, 2) not null,
  stock integer not null default 0,
  category_id bigint references public.categories(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.products enable row level security;

-- Create policies
create policy "Enable read access for all users" on public.products for select using (true);

-- Permissions
revoke select on public.products from anon;
